<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AgrupacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgrupacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPaginateAgrupaciones($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
               
        $dql = "SELECT a FROM App\Entity\Agrupacion a ORDER BY a.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
    public function getAllAgrupaciones(){
	$em=$this->getEntityManager();
        $dql = "SELECT a FROM App\Entity\Agrupacion a ORDER BY a.descripcion ASC ";
	$query = $em->createQuery($dql);
	return $query;
    }
    
    
    public function AnotacionInAgrupacion($agrupacion){
		$em=$this->getEntityManager();
        $dql = "SELECT a FROM App\Entity\Anotacion a where a.agrupacion = :agrupacion ";
        $query = $em->createQuery($dql);
		$query->setParameter('agrupacion', $agrupacion);
		if ($query->getResult()){
			return true;
		}
			return false;
		
	}
	
    
}
