<?php

namespace App\Repository;

/**
 * AnyoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnyoRepository extends \Doctrine\ORM\EntityRepository
{
}
