<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getPaginateClases($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
         
        
        $dql = "SELECT c FROM App\Entity\Clase c ORDER BY c.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
	public function getAllClases(){
        $em=$this->getEntityManager();
        $dql = "SELECT c FROM App\Entity\Clase c ORDER BY c.descripcion ASC ";
        $query = $em->createQuery($dql);
        return $query;
    }
	
	public function SubclaseInClase($clase){
		$em=$this->getEntityManager();
        $dql = "SELECT s FROM App\Entity\Subclase s where s.clase = :clase ";
        $query = $em->createQuery($dql);
		$query->setParameter('clase', $clase);
		if ($query->getResult()){
			return true;
		}
			return false;
		
	}
}
