<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getPaginateCuentas($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
               
        $dql = "SELECT c FROM App\Entity\Cuenta c ORDER BY c.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
	public function getAllCuentas(){
		$em=$this->getEntityManager();
        $dql = "SELECT c FROM App\Entity\Cuenta c ORDER BY c.descripcion ASC ";
		$query = $em->createQuery($dql);
		return $query;
	}
	
	
	
}
