<?php

namespace App\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * FormaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaPagoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaginateFormasPago($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
               
        $dql = "SELECT fp FROM App\Entity\FormaPago fp ORDER BY fp.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
	public function getAllFormasPago(){
		$em=$this->getEntityManager();
        $dql = "SELECT fp FROM App\Entity\FormaPago fp ORDER BY fp.descripcion ASC ";
		$query = $em->createQuery($dql);
		return $query;
	}
}
