<?php

namespace App\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PlanCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanCargoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaginatePlanesCargo($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
               
        $dql = "SELECT p FROM App\Entity\PlanCargo p ORDER BY p.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
	public function getAllPlanesCargo(){
		$em=$this->getEntityManager();
        $dql = "SELECT c FROM App\Entity\PlanCargo p ORDER BY p.descripcion ASC ";
		$query = $em->createQuery($dql);
		return $query;
	}
	
	
	
}
