<?php

namespace App\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * SubclaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubclaseRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	public function getPaginateSubclases($tamanyo = 3,$paginaActual = 1){
        $em=$this->getEntityManager();
         
        
        $dql = "SELECT s,c,cu FROM App\Entity\Subclase s JOIN s.clase c LEFT JOIN s.cuenta cu ORDER BY c.descripcion ASC,s.descripcion ASC ";
        $query = $em->createQuery($dql)
                               ->setFirstResult($tamanyo * ($paginaActual - 1))
                               ->setMaxResults($tamanyo);
 
        $paginator = new Paginator($query, $fetchJoinCollection = true);
 
        return $paginator;
    }
	
	public function getSubclases($clase){
		$em=$this->getEntityManager();
        $dql = "SELECT s FROM App\Entity\Subclase s where s.clase = :clase ";
        $query = $em->createQuery($dql);
		$query->setParameter('clase', $clase);
		return $query->execute();
	}

}
