<?php

namespace App\Repository;

/**
 * TipoFormaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFormaPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
